-- La Biblia Nos Habla
-- Versión 7.1 — Centro Multimedia
-- Ejecute este archivo completo una sola vez en Supabase SQL Editor.

create table if not exists media_items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  media_type text not null default 'video'
    check (media_type in ('video','audio','podcast','live','short')),
  category text,
  series_name text,
  scripture text,
  media_url text not null,
  thumbnail_url text,
  featured boolean default false,
  published boolean default false,
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

alter table media_items enable row level security;

drop policy if exists "Public reads published media" on media_items;
create policy "Public reads published media"
on media_items for select
using (published = true or public.is_staff());

drop policy if exists "Staff manages media" on media_items;
create policy "Staff manages media"
on media_items for all
to authenticated
using (public.is_staff())
with check (public.is_staff());

create index if not exists media_items_created_at_idx
on media_items (created_at desc);

create index if not exists media_items_published_idx
on media_items (published, featured);
