-- LA BIBLIA NOS HABLA
-- VERSION 8.0A - CENTRO PASTORAL
-- Ejecute este archivo completo UNA SOLA VEZ en Supabase SQL Editor.

-- 1. Perfiles y permisos
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'member'
    check (role in ('member','leader','editor','admin','pastor')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.email),
    'member'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

insert into public.profiles (id, full_name, role)
select id, coalesce(raw_user_meta_data->>'full_name', email), 'member'
from auth.users
on conflict (id) do nothing;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('leader','editor','admin','pastor')
  );
$$;

grant execute on function public.is_staff() to anon, authenticated;

drop policy if exists "Users read own profile" on public.profiles;
create policy "Users read own profile"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_staff());

drop policy if exists "Staff updates profiles" on public.profiles;
create policy "Staff updates profiles"
on public.profiles for update
to authenticated
using (public.is_staff())
with check (public.is_staff());

-- 2. Predicaciones: ampliar la tabla existente sin borrar contenido
create table if not exists public.sermons (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  created_at timestamptz default now()
);

alter table public.sermons add column if not exists scripture text;
alter table public.sermons add column if not exists preacher text default 'Pastor Gilberto Maldonado';
alter table public.sermons add column if not exists category text;
alter table public.sermons add column if not exists series_name text;
alter table public.sermons add column if not exists outline text;
alter table public.sermons add column if not exists youtube_url text;
alter table public.sermons add column if not exists audio_url text;
alter table public.sermons add column if not exists pdf_url text;
alter table public.sermons add column if not exists thumbnail_url text;
alter table public.sermons add column if not exists featured boolean default false;
alter table public.sermons add column if not exists published boolean default false;
alter table public.sermons add column if not exists created_by uuid references auth.users(id);

alter table public.sermons enable row level security;

drop policy if exists "Public Sermons" on public.sermons;
drop policy if exists "Public reads published sermons" on public.sermons;
create policy "Public reads published sermons"
on public.sermons for select
using (published = true or public.is_staff());

drop policy if exists "Staff manages sermons" on public.sermons;
create policy "Staff manages sermons"
on public.sermons for all
to authenticated
using (public.is_staff())
with check (public.is_staff());

create index if not exists sermons_created_at_idx
on public.sermons (created_at desc);

create index if not exists sermons_published_featured_idx
on public.sermons (published, featured);

-- 3. Tablas de seguimiento pastoral (se conservan si ya existen)
create table if not exists public.prayer_requests (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  phone text,
  request_type text,
  request_text text,
  status text default 'Nuevo',
  created_at timestamptz default now()
);

create table if not exists public.new_believers (
  id bigint generated by default as identity primary key,
  full_name text,
  email text,
  phone text,
  status text default 'Nuevo',
  created_at timestamptz default now()
);

alter table public.prayer_requests enable row level security;
alter table public.new_believers enable row level security;

drop policy if exists "Public inserts prayer requests" on public.prayer_requests;
create policy "Public inserts prayer requests"
on public.prayer_requests for insert
to anon, authenticated
with check (true);

drop policy if exists "Staff reads prayer requests" on public.prayer_requests;
create policy "Staff reads prayer requests"
on public.prayer_requests for select
to authenticated
using (public.is_staff());

drop policy if exists "Staff updates prayer requests" on public.prayer_requests;
create policy "Staff updates prayer requests"
on public.prayer_requests for update
to authenticated
using (public.is_staff())
with check (public.is_staff());

drop policy if exists "Public inserts new believers" on public.new_believers;
create policy "Public inserts new believers"
on public.new_believers for insert
to anon, authenticated
with check (true);

drop policy if exists "Staff reads new believers" on public.new_believers;
create policy "Staff reads new believers"
on public.new_believers for select
to authenticated
using (public.is_staff());

drop policy if exists "Staff updates new believers" on public.new_believers;
create policy "Staff updates new believers"
on public.new_believers for update
to authenticated
using (public.is_staff())
with check (public.is_staff());

-- IMPORTANTE:
-- Después de crear su usuario en Authentication > Users,
-- ejecute la siguiente línea cambiando el correo si fuera necesario:
--
-- update public.profiles
-- set role='pastor', full_name='Pastor Gilberto Maldonado'
-- where id=(select id from auth.users where email='labiblianoshablapodcast@gmail.com');
