-- LA BIBLIA NOS HABLA
-- VERSION 8.2A - PREDICACIONES PRO
-- Ejecute este archivo completo UNA SOLA VEZ en Supabase SQL Editor.

alter table public.sermons add column if not exists slug text;
alter table public.sermons add column if not exists summary text;
alter table public.sermons add column if not exists content_html text;
alter table public.sermons add column if not exists status text default 'draft';
alter table public.sermons add column if not exists published_at timestamptz;
alter table public.sermons add column if not exists seo_title text;
alter table public.sermons add column if not exists seo_description text;

update public.sermons
set slug = lower(regexp_replace(regexp_replace(coalesce(title,'predicacion'), '[^a-zA-Z0-9]+', '-', 'g'), '(^-|-$)', '', 'g')) || '-' || id
where slug is null or slug = '';

update public.sermons
set status = case when published then 'published' else 'draft' end
where status is null or status = '';

update public.sermons
set published_at = coalesce(published_at, created_at)
where published = true and published_at is null;

create unique index if not exists sermons_slug_unique_idx on public.sermons(slug);
create index if not exists sermons_status_idx on public.sermons(status, published_at desc);
create index if not exists sermons_category_idx on public.sermons(category);
create index if not exists sermons_series_idx on public.sermons(series_name);

create table if not exists public.sermon_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  created_at timestamptz default now()
);

create table if not exists public.sermon_series (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  created_at timestamptz default now()
);

alter table public.sermon_categories enable row level security;
alter table public.sermon_series enable row level security;

drop policy if exists "Public reads sermon categories" on public.sermon_categories;
create policy "Public reads sermon categories"
on public.sermon_categories for select using (true);

drop policy if exists "Staff manages sermon categories" on public.sermon_categories;
create policy "Staff manages sermon categories"
on public.sermon_categories for all to authenticated
using (public.is_staff()) with check (public.is_staff());

drop policy if exists "Public reads sermon series" on public.sermon_series;
create policy "Public reads sermon series"
on public.sermon_series for select using (true);

drop policy if exists "Staff manages sermon series" on public.sermon_series;
create policy "Staff manages sermon series"
on public.sermon_series for all to authenticated
using (public.is_staff()) with check (public.is_staff());

insert into public.sermon_categories(name,slug) values
('Salvación','salvacion'),('Fe','fe'),('Espíritu Santo','espiritu-santo'),
('Familia','familia'),('Discipulado','discipulado'),('Vida Cristiana','vida-cristiana')
on conflict do nothing;
