-- Registro privado de donaciones verificadas por PayPal
create table if not exists public.paypal_donations (
  id bigint generated by default as identity primary key,
  transaction_id text not null unique,
  donor_name text,
  payer_email text,
  gross_amount numeric(12,2) not null,
  fee_amount numeric(12,2),
  currency text not null default 'USD',
  payment_status text not null,
  donated_at timestamptz not null,
  raw_event jsonb,
  created_at timestamptz not null default now()
);

alter table public.paypal_donations enable row level security;

drop policy if exists "Staff reads PayPal donations" on public.paypal_donations;
create policy "Staff reads PayPal donations"
on public.paypal_donations for select
to authenticated
using (public.is_staff());

-- No existe política pública de escritura. Solamente el servidor, después de
-- verificar el mensaje con PayPal, puede guardar o actualizar una transacción.
create index if not exists paypal_donations_donated_at_idx
on public.paypal_donations (donated_at desc);
