create extension if not exists pgcrypto;

create table if not exists public.john_study_participants (
  id uuid primary key default gen_random_uuid(),
  participant_token text unique not null,
  full_name text not null,
  email text,
  created_at timestamptz not null default now(),
  last_activity_at timestamptz not null default now()
);

create table if not exists public.john_study_completions (
  id bigint generated by default as identity primary key,
  participant_id uuid not null references public.john_study_participants(id) on delete cascade,
  chapter smallint not null check (chapter between 1 and 21),
  completed_at timestamptz not null default now(),
  unique(participant_id,chapter)
);

create table if not exists public.john_study_milestones (
  id bigint generated by default as identity primary key,
  participant_id uuid not null references public.john_study_participants(id) on delete cascade,
  milestone smallint not null check (milestone in (5,10,15,20)),
  reached_at timestamptz not null default now(),
  seen_at timestamptz,
  unique(participant_id,milestone)
);

create index if not exists john_study_completions_participant_idx on public.john_study_completions(participant_id);
create index if not exists john_study_milestones_unseen_idx on public.john_study_milestones(seen_at) where seen_at is null;

alter table public.john_study_participants enable row level security;
alter table public.john_study_completions enable row level security;
alter table public.john_study_milestones enable row level security;
revoke all on public.john_study_participants,public.john_study_completions,public.john_study_milestones from anon,authenticated;
grant all on public.john_study_participants,public.john_study_completions,public.john_study_milestones to service_role;
grant usage,select on all sequences in schema public to service_role;
