-- Contador de instalaciones PWA - La Biblia Nos Habla
-- Ejecutar una sola vez en Supabase SQL Editor.

create table if not exists public.pwa_installs (
  id bigint generated by default as identity primary key,
  install_id uuid not null unique,
  platform text not null default 'unknown' check (platform in ('ios','android','desktop','unknown')),
  source text not null default 'unknown',
  installed_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create index if not exists pwa_installs_installed_at_idx
  on public.pwa_installs (installed_at desc);

alter table public.pwa_installs enable row level security;

-- No se crean políticas públicas: el registro y la lectura se hacen
-- exclusivamente desde rutas del servidor usando SUPABASE_SERVICE_ROLE_KEY.
