-- Reparación completa de la tabla de eventos
-- Ejecute este archivo una sola vez en Supabase → SQL Editor → Run.
-- Es seguro volver a ejecutarlo: no borra eventos ni fotografías existentes.

begin;

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  starts_at timestamptz,
  location text,
  published boolean default false,
  created_by uuid references auth.users(id),
  created_at timestamptz default now(),
  image_url text,
  image_path text
);

-- Completa instalaciones antiguas donde la tabla ya existía con menos columnas.
alter table public.events add column if not exists title text;
alter table public.events add column if not exists description text;
alter table public.events add column if not exists starts_at timestamptz;
alter table public.events add column if not exists location text;
alter table public.events add column if not exists published boolean default false;
alter table public.events add column if not exists created_by uuid references auth.users(id);
alter table public.events add column if not exists created_at timestamptz default now();
alter table public.events add column if not exists image_url text;
alter table public.events add column if not exists image_path text;

alter table public.events enable row level security;

drop policy if exists "Public reads published events" on public.events;
create policy "Public reads published events"
on public.events for select
using (published=true or public.is_staff());

drop policy if exists "Staff manages events" on public.events;
create policy "Staff manages events"
on public.events for all
to authenticated
using (public.is_staff())
with check (public.is_staff());

grant usage on schema public to anon, authenticated;
grant select on public.events to anon;
grant select,insert,update,delete on public.events to authenticated;
grant usage,select on all sequences in schema public to authenticated;

commit;

-- Obliga a PostgREST/Supabase a reconocer la estructura nueva.
notify pgrst, 'reload schema';

-- Las ocho comprobaciones deben aparecer en true.
select
  'Eventos preparados correctamente' as resultado,
  count(*) = 8 as estructura_completa,
  array_agg(column_name order by column_name) as columnas_encontradas
from information_schema.columns
where table_schema='public'
  and table_name='events'
  and column_name in (
    'title',
    'description',
    'starts_at',
    'location',
    'published',
    'created_by',
    'image_url',
    'image_path'
  );
