-- Registro privado de donaciones recibidas por PayPal
-- Ejecute este archivo una sola vez en Supabase -> SQL Editor.
-- Es idempotente y no elimina registros existentes.

begin;

create table if not exists public.paypal_donations (
  id bigint generated by default as identity primary key,
  transaction_id text not null unique,
  donor_name text,
  payer_email text,
  gross_amount numeric(12,2) not null check (gross_amount > 0),
  fee_amount numeric(12,2),
  currency text not null default 'USD',
  payment_status text not null default 'Unknown',
  donated_at timestamptz not null default now(),
  raw_event jsonb,
  created_at timestamptz not null default now()
);

alter table public.paypal_donations enable row level security;

drop policy if exists "Pastor and treasurer read PayPal donations" on public.paypal_donations;
create policy "Pastor and treasurer read PayPal donations"
on public.paypal_donations
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where id=auth.uid()
      and role in ('pastor','treasurer')
  )
);

-- Las inserciones y actualizaciones se realizan únicamente desde el servidor
-- con SUPABASE_SERVICE_ROLE_KEY; no se concede escritura al navegador.

commit;

notify pgrst, 'reload schema';

select
  'Registro privado de PayPal preparado correctamente' as resultado,
  to_regclass('public.paypal_donations') is not null as tabla_lista;
