-- La Biblia Nos Habla 2.0 - esquema inicial
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text default 'member',
  created_at timestamptz default now()
);

create table if not exists resources (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category text,
  scripture text,
  youtube_url text,
  file_url text,
  published boolean default false,
  created_at timestamptz default now()
);

create table if not exists prayer_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  request text not null,
  status text default 'received',
  created_at timestamptz default now()
);

create table if not exists missions (
  id bigint generated by default as identity primary key,
  title text not null,
  location text,
  description text,
  event_date date,
  published boolean default false,
  created_at timestamptz default now()
);

create table if not exists events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  starts_at timestamptz,
  location text,
  published boolean default false,
  created_at timestamptz default now()
);

alter table profiles enable row level security;
alter table resources enable row level security;
alter table prayer_requests enable row level security;
alter table missions enable row level security;
alter table events enable row level security;
