-- Gestor de contenido sin código — fotos, eventos y usuarios
alter table public.profiles add column if not exists email text;
alter table public.events add column if not exists image_url text;
alter table public.events add column if not exists image_path text;

create table if not exists public.gallery_items (
  id bigint generated by default as identity primary key,
  title text not null,
  alt_text text,
  category text not null default 'Iglesia',
  image_url text not null,
  storage_path text not null,
  published boolean not null default false,
  sort_order integer not null default 0,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.gallery_items enable row level security;

drop policy if exists "Public reads published gallery" on public.gallery_items;
create policy "Public reads published gallery"
on public.gallery_items for select
using (published=true or public.is_staff());

drop policy if exists "Staff manages gallery" on public.gallery_items;
create policy "Staff manages gallery"
on public.gallery_items for all
to authenticated
using (public.is_staff())
with check (public.is_staff());

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values (
  'site-media',
  'site-media',
  true,
  10485760,
  array['image/jpeg','image/png','image/webp','image/heic','image/heif']
)
on conflict (id) do update set
  public=excluded.public,
  file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "Public views site media" on storage.objects;
create policy "Public views site media"
on storage.objects for select
using (bucket_id='site-media');

drop policy if exists "Staff uploads site media" on storage.objects;
create policy "Staff uploads site media"
on storage.objects for insert
to authenticated
with check (bucket_id='site-media' and public.is_staff());

drop policy if exists "Staff updates site media" on storage.objects;
create policy "Staff updates site media"
on storage.objects for update
to authenticated
using (bucket_id='site-media' and public.is_staff())
with check (bucket_id='site-media' and public.is_staff());

drop policy if exists "Staff deletes site media" on storage.objects;
create policy "Staff deletes site media"
on storage.objects for delete
to authenticated
using (bucket_id='site-media' and public.is_staff());

create or replace function public.is_pastor()
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select exists(
    select 1 from public.profiles
    where id=auth.uid() and role='pastor'
  );
$$;

drop policy if exists "Pastor updates staff profiles" on public.profiles;
create policy "Pastor updates staff profiles"
on public.profiles for update
to authenticated
using (public.is_pastor())
with check (public.is_pastor());
