-- La Biblia Nos Habla 2.5 - Supabase
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'member' check (role in ('pastor','secretary','treasurer','media','member')),
  created_at timestamptz default now()
);

create table if not exists resources (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category text,
  scripture text,
  youtube_url text,
  file_url text,
  published boolean default false,
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

create table if not exists prayer_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text,
  request_type text,
  request text not null,
  status text not null default 'new'
    check (status in ('new','follow_up','attended','completed')),
  private_notes text,
  created_at timestamptz default now()
);

create table if not exists missions (
  id bigint generated by default as identity primary key,
  title text not null,
  location text,
  description text,
  event_date date,
  published boolean default false,
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

create table if not exists events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  starts_at timestamptz,
  location text,
  published boolean default false,
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

alter table profiles enable row level security;
alter table resources enable row level security;
alter table prayer_requests enable row level security;
alter table missions enable row level security;
alter table events enable row level security;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select exists(
    select 1 from profiles
    where id=auth.uid()
    and role in ('pastor','secretary','treasurer','media')
  );
$$;

drop policy if exists "Staff reads profiles" on profiles;
create policy "Staff reads profiles"
on profiles for select
to authenticated
using (public.is_staff() or id=auth.uid());

drop policy if exists "Public reads published resources" on resources;
create policy "Public reads published resources"
on resources for select
using (published=true or public.is_staff());

drop policy if exists "Staff manages resources" on resources;
create policy "Staff manages resources"
on resources for all
to authenticated
using (public.is_staff())
with check (public.is_staff());

drop policy if exists "Staff reads prayer requests" on prayer_requests;
create policy "Staff reads prayer requests"
on prayer_requests for select
to authenticated
using (public.is_staff());

drop policy if exists "Public submits prayer requests" on prayer_requests;
create policy "Public submits prayer requests"
on prayer_requests for insert
to anon,authenticated
with check (true);

drop policy if exists "Staff updates prayer requests" on prayer_requests;
create policy "Staff updates prayer requests"
on prayer_requests for update
to authenticated
using (public.is_staff())
with check (public.is_staff());

drop policy if exists "Public reads published missions" on missions;
create policy "Public reads published missions"
on missions for select
using (published=true or public.is_staff());

drop policy if exists "Staff manages missions" on missions;
create policy "Staff manages missions"
on missions for all
to authenticated
using (public.is_staff())
with check (public.is_staff());

drop policy if exists "Public reads published events" on events;
create policy "Public reads published events"
on events for select
using (published=true or public.is_staff());

drop policy if exists "Staff manages events" on events;
create policy "Staff manages events"
on events for all
to authenticated
using (public.is_staff())
with check (public.is_staff());
