'use client';

import {useEffect,useMemo,useRef,useState} from "react";
import {getRvr60Audio} from "@/lib/rvr60-audio";

type Timing={verse:number;start:number};
type Verse={number:number;text:string};
type AudioPayload={ok:boolean;audioUrl?:string;timings?:Timing[];filesetId?:string;error?:string};

export default function BibleAudioControls({language,bookCode,chapter,verses=[]}:{language:"qeqchi"|"rvr60";bookCode?:string;chapter?:number;verses?:Verse[]}){
 const label=language==="qeqchi"?"Q’eqchi’ · Li Santil Hu":"Español · RVR1960";
 const audioRef=useRef<HTMLAudioElement|null>(null); const cardRef=useRef<HTMLElement|null>(null);
 const [payload,setPayload]=useState<AudioPayload|null>(null); const [loading,setLoading]=useState(language==="rvr60"); const [speed,setSpeed]=useState(1); const [playing,setPlaying]=useState(false); const [progress,setProgress]=useState(0); const [showFloating,setShowFloating]=useState(false); const [activeVerse,setActiveVerse]=useState<number|null>(null);
 useEffect(()=>{let cancelled=false;setPlaying(false);setProgress(0);setShowFloating(false);setActiveVerse(null);const localAudio=language==="rvr60"&&bookCode&&chapter?getRvr60Audio(bookCode,chapter):null;if(!localAudio){setLoading(false);setPayload({ok:false,error:"Todavía no hemos subido el audio de este capítulo."});return;}setPayload({ok:true,audioUrl:localAudio,timings:[]});setLoading(language==="rvr60");if(language==="rvr60"&&bookCode&&chapter){fetch(`/api/bible-brain/rvr1960?book=${encodeURIComponent(bookCode)}&chapter=${chapter}`,{cache:"no-store"}).then(async r=>{const data=await r.json().catch(()=>null) as AudioPayload|null;if(cancelled||!data?.ok)return;if(Array.isArray(data.timings)&&data.timings.length)setPayload(c=>c?.ok?{...c,timings:data.timings,filesetId:data.filesetId}:c);}).catch(()=>{}).finally(()=>{if(!cancelled)setLoading(false);});}else setLoading(false);return()=>{cancelled=true;window.dispatchEvent(new CustomEvent("bible-audio-verse",{detail:{verse:null}}));};},[language,bookCode,chapter]);
 useEffect(()=>{const update=()=>{const card=cardRef.current;setShowFloating(Boolean(card&&card.getBoundingClientRect().bottom<0));};update();window.addEventListener("scroll",update,{passive:true});window.addEventListener("resize",update);return()=>{window.removeEventListener("scroll",update);window.removeEventListener("resize",update);};},[]);
 const timings=useMemo(()=>payload?.timings??[],[payload?.timings]); const ready=Boolean(payload?.ok&&payload.audioUrl);
 function emitVerse(verse:number|null){if(verse===activeVerse)return;setActiveVerse(verse);window.dispatchEvent(new CustomEvent("bible-audio-verse",{detail:{verse}}));}
 function startOffset(a:HTMLAudioElement){return language==="rvr60"&&Number.isFinite(a.duration)&&a.duration>15?15:0;}
 function estimatedVerse(a:HTMLAudioElement,offset:number){if(!verses.length||!Number.isFinite(a.duration)||a.duration<=offset)return null;const weights=verses.map(v=>{const text=v.text.trim();const words=text.split(/\s+/).filter(Boolean).length;const punctuation=(text.match(/[,.!?;:—-]/g)||[]).length;return Math.max(1,words+punctuation*.65);});const total=weights.reduce((s,w)=>s+w,0);const elapsed=Math.max(0,a.currentTime-offset);const readingDuration=Math.max(1,a.duration-offset);const target=Math.min(total,(elapsed/readingDuration)*total);let cumulative=0;for(let i=0;i<verses.length;i++){cumulative+=weights[i];if(target<cumulative)return verses[i].number;}return verses[verses.length-1]?.number??null;}
 function syncVerse(){const a=audioRef.current;if(!a)return;const offset=startOffset(a);setProgress(Number.isFinite(a.duration)&&a.duration>offset?Math.max(0,Math.min(100,(a.currentTime-offset)/(a.duration-offset)*100)):0);if(timings.length){let active:number|null=null;for(const t of timings){if(t.start<=a.currentTime)active=t.verse;else break;}emitVerse(active);return;}emitVerse(estimatedVerse(a,offset));}
 function skip(s:number){const a=audioRef.current;if(!a)return;a.currentTime=Math.max(startOffset(a),Math.min(a.duration||Infinity,a.currentTime+s));syncVerse();}
 function togglePlay(){const a=audioRef.current;if(!a)return;if(a.paused){if(a.currentTime<startOffset(a)||a.ended)a.currentTime=startOffset(a);void a.play().catch(()=>setPlaying(false));}else a.pause();}
 function toggleSpeed(){const opts=[1,1.25,1.5,.75];const next=opts[(opts.indexOf(speed)+1)%opts.length];setSpeed(next);if(audioRef.current)audioRef.current.playbackRate=next;}
 function controls(floating=false){return <div className={floating?"bibleAudioControls bibleAudioFloatingControls":"bibleAudioControls"}><button type="button" className="audioSkip" onClick={()=>skip(-10)} disabled={!ready}>↶</button><button type="button" className="audioPlay" onClick={togglePlay} disabled={!ready}>{playing?"❚❚":"▶"}</button><button type="button" className="audioSkip" onClick={()=>skip(10)} disabled={!ready}>↷</button><div className="audioProgress"><span style={{width:`${progress}%`}} /></div><button type="button" className="audioSpeed" onClick={toggleSpeed} disabled={!ready}>{speed}×</button></div>;}
 return <><section ref={cardRef} className="bibleAudioCard"><div className="bibleAudioHeader"><div className="bibleAudioIcon">🎧</div><div><small>ESCUCHAR LA BIBLIA</small><strong>{label}</strong></div><span className="bibleAudioBadge">Audio</span></div>{ready?<audio key={payload?.audioUrl} ref={audioRef} src={payload?.audioUrl} preload="metadata" onPlay={()=>{setPlaying(true);syncVerse();}} onPause={()=>setPlaying(false)} onLoadedMetadata={()=>{const a=audioRef.current;if(a){a.playbackRate=speed;a.currentTime=startOffset(a);syncVerse();}}} onTimeUpdate={syncVerse} onSeeked={syncVerse} onEnded={()=>{setPlaying(false);emitVerse(null);}} />:null}{controls()}<p className="bibleAudioStatus">{loading?"Preparando seguimiento de versículos…":ready?(timings.length?"Audio conectado · seguimiento con timestamps.":verses.length?`Audio conectado · seguimiento aproximado${activeVerse?` · versículo ${activeVerse}`:""}.`:"Audio conectado."):(payload?.error||"Audio no disponible.")}</p></section>{showFloating&&ready?<aside className="bibleAudioFloating"><div className="bibleAudioFloatingTitle"><span>🎧</span><strong>{label}{activeVerse?` · v.${activeVerse}`:""}</strong></div>{controls(true)}</aside>:null}</>;
}
