"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import KidsArt,{KidsIcon,Lumi} from "@/components/KidsArt";
import {kidsLesson,kidsQuestions,gradeKidsQuiz} from "@/lib/kids";
import type {KidsAge} from "@/lib/kids";
import {createKidsNarrator,kidsQuestionScenes,questionNarration} from "@/lib/kids-narration";
import styles from "@/app/kids/kids.module.css";

export default function KidsLesson({age,slot}:{age:KidsAge;slot:number}){
 const [scene,setScene]=useState(0),[playing,setPlaying]=useState(false),[voice,setVoice]=useState(false);
 const [answers,setAnswers]=useState<number[]>([-1,-1,-1]),[checked,setChecked]=useState(false),[consent,setConsent]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const [selectedSlot,setSelectedSlot]=useState(slot);const [activeAudio,setActiveAudio]=useState<string|null>(null),[audioError,setAudioError]=useState("");
 const narrator=useRef<ReturnType<typeof createKidsNarrator>|null>(null);const lastScene=kidsLesson.scenes.length-1;
 const text=age==="4-6"?kidsLesson.scenes[scene].young:kidsLesson.scenes[scene].older;const score=gradeKidsQuiz(age,answers);
 useEffect(()=>{let live=true;const available="speechSynthesis" in window&&"SpeechSynthesisUtterance" in window;setVoice(available);if(available)narrator.current=createKidsNarrator(window.speechSynthesis,text=>new SpeechSynthesisUtterance(text),key=>{if(live)setActiveAudio(key);},()=>{if(live)setAudioError("No pudimos reproducir la voz. Puede leer el texto o intentarlo de nuevo.");});return()=>{live=false;narrator.current?.stop();narrator.current=null;};},[]);
 useEffect(()=>{if(!playing)return;const timer=window.setTimeout(()=>{if(scene===lastScene)setPlaying(false);else setScene(value=>value+1);},age==="4-6"?14000:20000);return()=>window.clearTimeout(timer);},[playing,scene,age,lastScene]);
 useEffect(()=>{narrator.current?.stop();},[scene]);
 function move(next:number){setPlaying(false);narrator.current?.stop();setScene(next);}function speak(key:string,content:string){setPlaying(false);setAudioError("");narrator.current?.toggle(key,content,age==="4-6"?.8:.9);}
 async function save(){setSaving(true);setMessage("");try{const response=await fetch("/api/kids/progreso",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lesson:kidsLesson.id,age,slot:selectedSlot,answers,adultConsent:consent})});const result=await response.json();setMessage(response.ok?"Progreso guardado. Puede verlo en el espacio para padres.":result.error||"No se pudo guardar. Intente nuevamente.");}catch{setMessage("No se pudo conectar. Las respuestas siguen aquí mientras mantenga esta página abierta.");}finally{setSaving(false);}}
 return <>
 <section className={styles.story} aria-label="Historia animada"><div className={styles.stage} key={scene}><KidsArt scene={scene} onVideoPlay={()=>speak(`video-${scene}`,`Escena ${scene+1}. ${kidsLesson.scenes[scene].title}. ${text}`)} onVideoPause={()=>narrator.current?.stop()}/></div><div className={styles.storyText}><p className={styles.eyebrow}>Escena {scene+1} de {kidsLesson.scenes.length} · {age} años</p><h2>{kidsLesson.scenes[scene].title}</h2><p>{text}</p><div className={styles.controls}><button onClick={()=>move(Math.max(0,scene-1))} disabled={scene===0}>← Anterior</button><button onClick={()=>{narrator.current?.stop();if(scene===lastScene)setScene(0);setPlaying(value=>!value);}} aria-pressed={playing}>{playing?"Pausar escenas":"Ver escenas automáticamente"}</button><button onClick={()=>move(Math.min(lastScene,scene+1))} disabled={scene===lastScene}>Siguiente →</button>{voice&&<button onClick={()=>speak(`scene-${scene}`,`Escena ${scene+1}. ${kidsLesson.scenes[scene].title}. ${text}`)} aria-pressed={activeAudio===`scene-${scene}`}>{activeAudio===`scene-${scene}`?`Detener narración en español · escena ${scene+1}`:`Escuchar escena ${scene+1} en español`}</button>}</div><p className={styles.hint}>Toque ▶ en el video: la imagen y la narración en español comenzarán juntas. El audio original en inglés permanece apagado.</p><p className={styles.audioStatus} role="status">{activeAudio===`video-${scene}`||activeAudio===`scene-${scene}`?`Narración en español de la escena ${scene+1}: ${kidsLesson.scenes[scene].title}`:""}</p></div></section>
 <aside className={styles.lumi}><Lumi/><p><strong>¡Soy Lumi!</strong> Recordemos juntos: podemos confiar en Dios y pedir ayuda. Nunca imites el uso de una honda ni lances piedras a personas o animales.</p></aside><p role="status">{audioError}</p>
 <section className={styles.panel} aria-labelledby="kids-quiz"><p className={styles.eyebrow}>Aprendemos jugando</p><h2 id="kids-quiz">¿Qué descubriste?</h2><p>Primero escucha o lee la pregunta y sus opciones. Si necesitas recordar, escucha la parte de la historia indicada en esa misma tarjeta. Luego elige A, B o C.</p>{!voice&&<p className={styles.hint}>La lectura en voz no está disponible en este navegador. Todo el contenido se puede leer con un adulto.</p>}{kidsQuestions[age].map((question,index)=>{const related=kidsQuestionScenes[age][index],story=kidsLesson.scenes[related],questionKey=`question-${index}`,storyKey=`context-${index}`;const isActive=activeAudio===questionKey||activeAudio===storyKey;return <fieldset key={index} className={`${styles.question} ${isActive?styles.questionPlaying:""}`} aria-describedby={`kids-related-${index}`}><legend>Pregunta {index+1}. {question.prompt}</legend><div className={styles.questionAudio}><p id={`kids-related-${index}`} className={styles.hint}><strong>Historia para esta pregunta:</strong> escena {related+1} · {story.title}</p>{voice&&<div className={styles.controls}><button type="button" aria-pressed={activeAudio===questionKey} onClick={()=>speak(questionKey,questionNarration(question,index))}>{activeAudio===questionKey?`Detener audio de pregunta ${index+1}`:`Escuchar pregunta ${index+1} y opciones`}</button><button type="button" aria-pressed={activeAudio===storyKey} onClick={()=>speak(storyKey,`Historia para la pregunta ${index+1}. Escena ${related+1}: ${story.title}. ${age==="4-6"?story.young:story.older}`)}>{activeAudio===storyKey?"Detener parte de la historia":`Escuchar parte de la historia · escena ${related+1}`}</button></div>}</div><div className={styles.options}>{question.options.map((option,choice)=><label key={choice} className={answers[index]===choice?styles.selected:""}><input type="radio" name={`kids-q-${index}`} checked={answers[index]===choice} onChange={()=>{setAnswers(previous=>previous.map((value,i)=>i===index?choice:value));setChecked(false);setMessage("");}}/><KidsIcon kind={option.icon}/><span><b className={styles.optionLetter}>{String.fromCharCode(65+choice)}</b>{option.text}</span></label>)}</div>{checked&&<p className={styles.explanation}>{answers[index]===question.answer?"✓ ¡Bien! ":"Vamos a aprender: "}{question.explanation}</p>}</fieldset>;})}<button className={styles.primary} disabled={score===null} onClick={()=>setChecked(true)}>Ver mis respuestas</button>{checked&&<div className={styles.result} role="status"><strong>{score} de 3 respuestas correctas</strong><p>{score===3?"¡Muy bien! Ahora comparte con tu familia lo que aprendiste.":"¡Gracias por intentarlo! Lee las explicaciones y vuelve a elegir si lo deseas."}</p></div>}</section>
 <section className={styles.panel}><p className={styles.eyebrow}>Para hacer en familia</p><h2>Tu hoja de actividades</h2><p>{age==="4-6"?"Colorea, cuenta cinco piedras y conversa con un adulto sobre cómo David confió en Dios.":"Ordena la historia, responde con tus propias palabras y prepara un plan para pedir ayuda."}</p><a className={styles.primary} href={`/api/kids/hoja?edad=${age}`}>Descargar hoja PDF · {age} años</a><p className={styles.hint}>Una página, tamaño carta. Lista para imprimir en blanco y negro.</p><Link href="/biblia/1-samuel/17">Leer 1 Samuel 17 en nuestra Biblia →</Link></section>
 {checked&&<section className={styles.panel}><h2>Espacio para el adulto</h2><p>Guardar es opcional. Solo se registra el grupo de edad, el número de explorador, el resultado más reciente y la fecha.</p><label className={styles.field}>Guardar para<select value={selectedSlot} onChange={event=>setSelectedSlot(Number(event.target.value))}>{[1,2,3].map(value=><option key={value} value={value}>Explorador {value}</option>)}</select></label><label className={styles.consent}><input type="checkbox" checked={consent} onChange={event=>setConsent(event.target.checked)}/>Soy el adulto responsable y autorizo guardar este resultado en mi cuenta.</label><button className={styles.primary} disabled={!consent||saving} onClick={save}>{saving?"Guardando…":"Guardar con mi cuenta de adulto"}</button><p role="status">{message}</p><Link href="/kids/padres">Entrar o crear cuenta de adulto →</Link></section>}</>;
}
