'use client';

import {useEffect,useRef,useState} from "react";
const AUDIO_VERSE_EVENT="bible-audio-verse";
type VerseTimingInput={number:number;text:string};
export default function QeqchiChapterAudio({src,bookName,chapter,verses}:{src?:string;bookName:string;chapter:number;verses:VerseTimingInput[];}){
 const player=useRef<HTMLAudioElement>(null);const cardRef=useRef<HTMLElement|null>(null);const [failed,setFailed]=useState(false);const [playing,setPlaying]=useState(false);const [progress,setProgress]=useState(0);const [speed,setSpeed]=useState(1);const [activeVerse,setActiveVerse]=useState<number|null>(null);const [showFloating,setShowFloating]=useState(false);const label=`${bookName} ${chapter} · Q’eqchi’`;
 function publishVerse(number:number|null){setActiveVerse(number);window.dispatchEvent(new CustomEvent(AUDIO_VERSE_EVENT,{detail:{verse:number}}));}
 useEffect(()=>{const update=()=>{const card=cardRef.current;setShowFloating(Boolean(card&&card.getBoundingClientRect().bottom<0&&src&&!failed));};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{window.removeEventListener('scroll',update);window.removeEventListener('resize',update);publishVerse(null);};},[src,failed]);
 function syncVerse(){const audio=player.current;if(audio)setProgress(Number.isFinite(audio.duration)&&audio.duration>0?audio.currentTime/audio.duration*100:0);if(!audio||!verses.length||!Number.isFinite(audio.duration)||audio.duration<=0)return;const PAUSE_WEIGHT=7;const weights=verses.map(v=>{const text=v.text.trim();const words=text.split(/\s+/).filter(Boolean).length;const punctuation=(text.match(/[,.!?;:—-]/g)||[]).length;return Math.max(1,words+punctuation*PAUSE_WEIGHT/10);});const totalWeight=weights.reduce((sum,w)=>sum+w,0);const INTRO_SECONDS=10;const FOLLOW_DELAY_SECONDS=.7;const readingDuration=Math.max(1,audio.duration-INTRO_SECONDS);const t=Math.max(0,audio.currentTime-INTRO_SECONDS-FOLLOW_DELAY_SECONDS);if(audio.currentTime<INTRO_SECONDS){if(activeVerse!==verses[0]?.number)publishVerse(verses[0]?.number??1);return;}const target=Math.min(totalWeight,(t/readingDuration)*totalWeight);let cumulative=0;let current=verses[0]?.number??1;for(let i=0;i<verses.length;i++){cumulative+=weights[i];current=verses[i].number;if(target<cumulative)break;}if(current!==activeVerse)publishVerse(current);}
 function skip(seconds:number){const a=player.current;if(!a)return;a.currentTime=Math.max(0,Math.min(Number.isFinite(a.duration)?a.duration:Infinity,a.currentTime+seconds));syncVerse();}
 function toggle(){const a=player.current;if(!a)return;if(a.paused)void a.play().catch(()=>setFailed(true));else a.pause();}
 function changeSpeed(){const rates=[1,1.25,1.5,.75];const next=rates[(rates.indexOf(speed)+1)%rates.length];setSpeed(next);if(player.current)player.current.playbackRate=next;}
 const controls=(floating=false)=><div className={floating?'bibleAudioControls bibleAudioFloatingControls':'bibleAudioControls'}><button type="button" className="audioSkip" aria-label="Retroceder 10 segundos" disabled={!src||failed} onClick={()=>skip(-10)}>↶</button><button type="button" className="audioPlay" aria-label={playing?'Pausar':'Reproducir'} disabled={!src||failed} onClick={toggle}>{playing?'❚❚':'▶'}</button><button type="button" className="audioSkip" aria-label="Adelantar 10 segundos" disabled={!src||failed} onClick={()=>skip(10)}>↷</button><div className="audioProgress" aria-hidden="true"><span style={{width:`${progress}%`}}/></div><button type="button" className="audioSpeed" disabled={!src||failed} onClick={changeSpeed}>{speed}×</button></div>;
 return <><section ref={cardRef} className="bibleAudioCard" aria-label={`Audio bíblico ${label}`}><div className="bibleAudioHeader"><div className="bibleAudioIcon" aria-hidden="true">🎧</div><div><small>ESCUCHAR LA BIBLIA</small><strong>{label}</strong></div><span className="bibleAudioBadge">Audio original</span></div>{controls()}{src?<><audio ref={player} preload="metadata" src={src} aria-label={`Escuchar ${label}`} style={{width:'100%',marginTop:'16px'}} onError={()=>setFailed(true)} onCanPlay={()=>{setFailed(false);syncVerse();}} onLoadedMetadata={syncVerse} onTimeUpdate={syncVerse} onSeeked={syncVerse} onPlay={()=>{setPlaying(true);syncVerse();}} onPause={()=>{setPlaying(false);syncVerse();}} onEnded={()=>{setPlaying(false);publishVerse(null);}}>Su navegador no admite la reproducción de audio.</audio>{failed&&<div role="status" className="bibleAudioStatus"><p>No pudimos cargar este audio. Compruebe su conexión e intente nuevamente.</p><button type="button" className="btn secondary" onClick={()=>{setFailed(false);player.current?.load();}}>Volver a cargar el audio</button></div>}<p className="bibleAudioStatus">Capítulo completo · Audio original en Q’eqchi’{activeVerse?<> · Siguiendo versículo <strong>{activeVerse}</strong></>:null}</p></>:<p className="bibleAudioStatus">Audio pendiente de incorporar para este capítulo.</p>}</section>{showFloating&&<aside className="bibleAudioFloating" aria-label={`Controles flotantes de ${label}`}><div className="bibleAudioFloatingTitle"><span>🎧</span><strong>{label}{activeVerse?` · v.${activeVerse}`:''}</strong></div>{controls(true)}</aside>}</>;
}
